import os
API_ID = int(os.environ.get("API_ID", None))
API_HASH = os.environ.get("API_HASH", None) 
BOT_TOKEN = os.environ.get("BOT_TOKEN", None) 
OPENAI_KEY = os.environ.get("OPENAI_KEY",None)
BOT_USERNAME = os.environ.get("BOT_USERNAME" ,None) 
SUDO=os.environ.get("SUDO","6793963086")
BOT_NAME = os.environ.get("BOT_NAME",None)
START_IMG = os.environ.get("START_IMG","https://telegra.ph/file/0838df903f23bf2e37b9d.jpg")
STKR = os.environ.get("STKR","CAACAgQAAxkBAAEQ245ljYcpjiUzNlnqZayXwYGXQdQUYgAC2Q8AAnsbSFJTlxo-p_AUAAEzBA")
BANNED_USERS=os.environ.get("BANNED_USERS",None)
UPDATE_CHNL = os.environ.get("UPDATE_CHNL",None)
OWNER_USERNAME = os.environ.get("OWNER_USERNAME",None)
SUDO=os.environ.get("SUDO","6793963086")
SUPPORT_GRP = os.environ.get("SUPPORT_GRP","")
BARD_TOKEN=os.environ.get("BARD_TOKEN","")
